update

diff --git a/.github/workflows/checks_callable.yml b/.github/workflows/checks_callable.yml
--- a/.github/workflows/checks_callable.yml
+++ b/.github/workflows/checks_callable.yml
@@ -5,27 +5,38 @@ jobs:
     name: Code and dependency checks
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - name: latest version
+        id: ghd
+        uses: proudust/gh-describe@v2
 
-      - name: Setup Bun
-        uses: oven-sh/setup-bun@v1
-        with:
-          bun-version: 1.1.33
-
-      - name: Install dependencies
-        run: bun install
-
-      - name: Run unit tests
-        run: bun run test
-
-      - name: Run linter
-        run: bun run lint
-
-      - name: Check licenses
+      - name: Run Version Check
         run: |
-          npx license-checker --onlyAllow "MIT;Apache-2.0;ISC;BSD-2-Clause;Python-2.0;CC-BY-4.0;BSD-3-Clause;BlueOak-1.0.0;CC0-1.0;0BSD;CC-BY-3.0"
-          if [ $? -ne 0 ]; then
-            echo "License check failed!"
-            exit 1
-          fi
+          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
+          last_version="${{ steps.ghd.outputs.tag }}"
+          echo "Last released version: $last_version"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Checkout code
+      #   uses: actions/checkout@v3
+
+      # - name: Setup Bun
+      #   uses: oven-sh/setup-bun@v1
+      #   with:
+      #     bun-version: 1.1.33
+
+      # - name: Install dependencies
+      #   run: bun install
+
+      # - name: Run unit tests
+      #   run: bun run test
+
+      # - name: Run linter
+      #   run: bun run lint
+
+      # - name: Check licenses
+      #   run: |
+      #     npx license-checker --onlyAllow "MIT;Apache-2.0;ISC;BSD-2-Clause;Python-2.0;CC-BY-4.0;BSD-3-Clause;BlueOak-1.0.0;CC0-1.0;0BSD;CC-BY-3.0"
+      #     if [ $? -ne 0 ]; then
+      #       echo "License check failed!"
+      #       exit 1
+      #     fi
